#!/bin/bash
#environment for the python script
source /opt/gridengine/default/common/settings.sh
#export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/annoroad/share/software/install/Python-3.3.2/lib
#export PYTHONPATH=${PYTHONPATH}:$(cd `dirname $0`; pwd)/python
export DRMAA_LIBRARY_PATH=/opt/gridengine/lib/lx26-amd64/libdrmaa.so
export QSUB_SGE_PY_PATH=$(cd `dirname $0`; pwd)/qsub_sge_drmaa.py
export QSUB_SGE_SH_PATH=$(cd `dirname $0`; pwd)/qsub_sge

 /annoroad/share/software/install/Python-3.3.2/bin/python3 $QSUB_SGE_PY_PATH "$@"
